[build]
  publish = "public"           # o la cartella che Netlify deve servire (ad es. la cartella dove vengono messi gli .html)
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
